name: Release

on:
  workflow_run:
      workflows: ["Update Manifest"]
      types:
        - completed

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
  # todo: auto release in pipeline. once we figure out
  # how to have the released version include the manifest update
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
      - name: Pack packs
        run: |
          npm install -g @foundryvtt/foundryvtt-cli
          fvtt package pack -n "rsk-capes" --in ./packs/src --out ../packs
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.version.outputs.semVer }}
          release_name: Release ${{ needs.version.outputs.semVer }}
          draft: false
          prerelease: false