name: Release

on:
  workflow_run:
      workflows: ["Update Manifest"]
      types:
        - completed

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
  # todo: auto release in pipeline. once we figure out
  # how to have the released version include the manifest update
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
      - name: Pack packs
        run: |
          npm install -g @foundryvtt/foundryvtt-cli
          mkdir -p /home/runner/work/rsk-system/Data
          fvtt configure set dataPath "/home/runner/work/rsk-system/Data"
          fvtt package workon "rsk-system" --type "System"
          fvtt package pack -n "rsk-capes" --in ./packs/src/rsk-capes --out ./packs/rsk-capes

      - name: Zip Files
        run: zip -r "./rsk-system.zip" ./*
      - name: Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{needs.version.outputs.semVer}}
          allowUpdates: false
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./rsk-system.zip"
          tag: ${{needs.version.outputs.semVer}}