name: Update Manifest

on:
  workflow_dispatch:


jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
  manifest:
    name: Update Manifest
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Manifest
        run: |
          sed -i 's/\b[0-9]\+\.[0-9]\+\.[0-9]\+\b/${{ needs.version.outputs.semVer }}/g' system.json

          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update manifest"
          git push